//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProjectBrief_PartB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments_per_Course_per_Student
    {
        public string Assignment_Title { get; set; }
        public int CourseId { get; set; }
        public string Course_Title { get; set; }
        public int StudentId { get; set; }
        public string Student_FirstName { get; set; }
        public string Student_LastName { get; set; }
    }
}
