//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProjectBrief_PartB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignments
    {
        public int AssignmentId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SubDateTime { get; set; }
        public Nullable<int> OralMark { get; set; }
        public Nullable<int> TotalMark { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Students Students { get; set; }

        public override string ToString()
        {
            return ($"Assignment Title: {Title}| Description: {Description}| Submission Date: {SubDateTime}| OralMark: {OralMark}| TotalMark: {TotalMark} ");
        }
    }
}
