//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProjectBrief_PartB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesTrainers
    {
        public int CoursesTrainersId { get; set; }
        public int CourseId { get; set; }
        public int TrainerId { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Trainers Trainers { get; set; }
    }
}
