//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndividualProjectBrief_PartB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndividualProjectBrief_Part_BEntities : DbContext
    {
        public IndividualProjectBrief_Part_BEntities()
            : base("name=IndividualProjectBrief_Part_BEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<CoursesStudents> CoursesStudents { get; set; }
        public virtual DbSet<CoursesTrainers> CoursesTrainers { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trainers> Trainers { get; set; }
        public virtual DbSet<AllCourses> AllCourses { get; set; }
        public virtual DbSet<AllStudents> AllStudents { get; set; }
        public virtual DbSet<AllTrainers> AllTrainers { get; set; }
        public virtual DbSet<Assignment_per_Course> Assignment_per_Course { get; set; }
        public virtual DbSet<Assignments_per_Course_per_Student> Assignments_per_Course_per_Student { get; set; }
        public virtual DbSet<Students_In_More_Than_One_Course> Students_In_More_Than_One_Course { get; set; }
        public virtual DbSet<Students_per_Course> Students_per_Course { get; set; }
        public virtual DbSet<Trainers_per_Course> Trainers_per_Course { get; set; }
    }
}
